### ISSUE TITLE
File size of extracted pages same as source

### ISSUE THREAD

**Issue by loxK** [bebenlebricolo/pdfmixtool#2]
When I extract a single page from a PDF the resulting file size is the same as the source file (version 1.1.1)

**Comment by bebenlebricolo** [comment]
Hi ! Oh I see, this fork is stalled since a long time. I recommend you check Scarpetta's Gitlab repository instead, I just forked his repo a long time ago to try to get it to compile on windows and few other things, but nothing since then.

I am pretty sure Marco will be glad to have a look at your issue (if it is still an issue with the most recent developments of his own).

Nonetheless, I suggest you add a bit more details in the issue title and in the issue's body when you open it again on Gitlab, just by reading it I don't know what is the problem and what you expect as an end user.  

Regards

Edit : closing this issue as there is nothing I can do here, I should take down my fork instead so that other end users like you are not mislead 🤔
